version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "**/Rust/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "**/{Type,Java}Script" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
