name: Rust tests

on:
  schedule:
  - cron: "0 1 * * *"
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches: [ "main" ]
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust with caching
      uses: cubist-labs/cubist/.github/actions/rust-cache@main
      with:
        key: rust-tests
        additional-restore-key: rust-tests

    - name: Install Cubist CLI
      uses: cubist-labs/cubist/.github/actions/run-with-ssh-key@main
      with:
        secret-ssh-key: ${{ secrets.CUBIST_DEV_READONLY_BOT_SSH_PRIVATE_KEY }}
        run: cargo --config net.git-fetch-with-cli=true install --locked --force --git ssh://git@github.com/cubist-labs/cubist cubist-cli

    - name: Test Storage
      uses: ./.github/actions/rust-test
      with:
        template: ./Storage/Rust
        secret-ssh-key: ${{ secrets.CUBIST_DEV_READONLY_BOT_SSH_PRIVATE_KEY }}

    - name: Test TokenBridge
      uses: ./.github/actions/rust-test
      with:
        template: ./TokenBridge/Rust
        secret-ssh-key: ${{ secrets.CUBIST_DEV_READONLY_BOT_SSH_PRIVATE_KEY }}

    - name: Test MPMC
      uses: ./.github/actions/rust-test
      with:
        template: ./MPMC/Rust
        secret-ssh-key: ${{ secrets.CUBIST_DEV_READONLY_BOT_SSH_PRIVATE_KEY }}

    # Only run a single instance of this workflow per branch/tag/node-version
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true
